### ISSUE TITLE
Suppress ConnectionRefusedError stacktraces while starting model server

### ISSUE THREAD

**Issue by walegahaha** [bveliqi/adversarial-vision-challenge#15]
```
(pytorch) ➜  resnet18_model_baseline git:(master) ✗ avc-test-model .
running avc-test-model
running avc-test-setup
Basic setup tests
-----------------
Python version: 3.5
Docker installed & running: ✓
Nvidia-docker installed: ✓
Crowdai_repo2docker installed: ✓
AVC package up-to-date: ✓

Building docker image of submission
-----------------------------------
Submission folder: "."
[Repo2Docker] Looking for repo2docker_config in /home/walegahaha/walegahaha/NIPS_adversarial/resnet18_model_baseline

FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

# avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Set up locales properly
RUN apt-get update && \
    apt-get install --yes --no-install-recommends locales wget bzip2 && \
    apt-get purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# Use bash as default shell, rather than sh
ENV SHELL /bin/bash

# Set up user
ARG NB_USER
ARG NB_UID
ENV USER ${NB_USER}
ENV HOME /home/${NB_USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER}
WORKDIR ${HOME}

RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
       less \
       npm \
       unzip \
       && apt-get purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8888

# Almost all environment variables
ENV APP_BASE /srv
ENV CONDA_DIR ${APP_BASE}/conda
ENV NB_PYTHON_PREFIX ${CONDA_DIR}
ENV KERNEL_PYTHON_PREFIX ${NB_PYTHON_PREFIX}
# Special case PATH
ENV PATH ${CONDA_DIR}/bin:$HOME/.local/bin:${PATH}
# If scripts required during build are present, copy them

COPY conda/install-miniconda.bash /tmp/install-miniconda.bash

COPY conda/environment.py-3.6.frozen.yml /tmp/environment.yml
RUN bash /tmp/install-miniconda.bash && \
rm /tmp/install-miniconda.bash /tmp/environment.yml



# Copy and chown stuff. This doubles the size of the repo, because
# you can't actually copy as USER, only as root! Thanks, Docker!
USER root
COPY src/ ${HOME}
RUN chown -R ${NB_USER}:${NB_USER} ${HOME}

# Run assemble scripts! These will actually build the specification
# in the repository into the image.
RUN apt-get update && \
apt-get install --yes --no-install-recommends git && \
apt-get purge && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

USER ${NB_USER}
RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"


# Container image Labels!
# Put these at the end, since we don't want to rebuild everything
# when these change! Did I mention I hate Dockerfile cache semantics?


# We always want containers to run as non-root
USER ${NB_USER}

# Make sure that postBuild scripts are marked executable before executing them
# Specify the default command to run
CMD ["jupyter", "notebook", "--ip", "0.0.0.0"]

Using PythonBuildPack builder
Step 1/32 : FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04
 ---> e0e1f862b848
Step 2/32 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 14fba472db07
Step 3/32 : RUN apt-get update &&     apt-get install --yes --no-install-recommends locales wget bzip2 &&     apt-get purge &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 5b8dd4f1bee9
Step 4/32 : RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
 ---> Using cache
 ---> 2237631de4db
Step 5/32 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> 89bc656418ce
Step 6/32 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> bd338ffaf113
Step 7/32 : ENV LANGUAGE en_US.UTF-8
 ---> Using cache
 ---> 81bbf4572b83
Step 8/32 : ENV SHELL /bin/bash
 ---> Using cache
 ---> 3c96c103859a
Step 9/32 : ARG NB_USER
 ---> Using cache
 ---> 2ed8bfe9d56c
Step 10/32 : ARG NB_UID
 ---> Using cache
 ---> aa799d0da4bf
Step 11/32 : ENV USER ${NB_USER}
 ---> Using cache
 ---> 00d187889ce1
Step 12/32 : ENV HOME /home/${NB_USER}
 ---> Using cache
 ---> 70903cbb9b55
Step 13/32 : RUN adduser --disabled-password     --gecos "Default user"     --uid ${NB_UID}     ${NB_USER}
 ---> Using cache
 ---> 12c53f9e206e
Step 14/32 : WORKDIR ${HOME}
 ---> Using cache
 ---> d743a87ae7c5
Step 15/32 : RUN apt-get update &&     apt-get install --yes --no-install-recommends        less        npm        unzip        && apt-get purge &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 0a8aa883f465
Step 16/32 : EXPOSE 8888
 ---> Using cache
 ---> ce4844ee2db7
Step 17/32 : ENV APP_BASE /srv
 ---> Using cache
 ---> 9c4fe8304470
Step 18/32 : ENV CONDA_DIR ${APP_BASE}/conda
 ---> Using cache
 ---> aa63f8633b49
Step 19/32 : ENV NB_PYTHON_PREFIX ${CONDA_DIR}
 ---> Using cache
 ---> 1f750a78fb3b
Step 20/32 : ENV KERNEL_PYTHON_PREFIX ${NB_PYTHON_PREFIX}
 ---> Using cache
 ---> e24ee55df126
Step 21/32 : ENV PATH ${CONDA_DIR}/bin:$HOME/.local/bin:${PATH}
 ---> Using cache
 ---> f606776e661a
Step 22/32 : COPY conda/install-miniconda.bash /tmp/install-miniconda.bash
 ---> Using cache
 ---> 2f0810c0cb21
Step 23/32 : COPY conda/environment.py-3.6.frozen.yml /tmp/environment.yml
 ---> Using cache
 ---> 9e495cb9e855
Step 24/32 : RUN bash /tmp/install-miniconda.bash && rm /tmp/install-miniconda.bash /tmp/environment.yml
 ---> Using cache
 ---> cf58131b8da6
Step 25/32 : USER root
 ---> Using cache
 ---> 68d4880c3908
Step 26/32 : COPY src/ ${HOME}
 ---> Using cache
 ---> f03127550df5
Step 27/32 : RUN chown -R ${NB_USER}:${NB_USER} ${HOME}
 ---> Using cache
 ---> 7f4f047813f5
Step 28/32 : RUN apt-get update && apt-get install --yes --no-install-recommends git && apt-get purge && apt-get clean && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> f5caf3e17bef
Step 29/32 : USER ${NB_USER}
 ---> Using cache
 ---> 334dbd4861d3
Step 30/32 : RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"
 ---> Using cache
 ---> c1d1d83c3d3a
Step 31/32 : USER ${NB_USER}
 ---> Using cache
 ---> c0644fb7813b
Step 32/32 : CMD ["jupyter", "notebook", "--ip", "0.0.0.0"]
 ---> Using cache
 ---> b7e93de7fdac
{"aux": {"ID": "sha256:b7e93de7fdac931a4bbd15277b9dfa4a6d9598e581d4734ec7a9e08e1b64bd85"}}Successfully built b7e93de7fdac
Successfully tagged avc/model_submission:latest
Building image from cache (if exists)... ✓
avc_test_model_submission
Removing existing submission container... ✓
Starting container on port 56451 using the command 
 
 NV_GPU=0 nvidia-docker run --expose=56451 -d -p 56451:56451 -e GPU=0 -e MODEL_PORT=56451 --name=avc_test_model_submission avc/model_submission bash run.sh
ec046c213aa434cc172f3c5c8c01b1c9f6b9c852e74056499cfe80fc0dfbab52
Received IP of server:  172.17.0.2
Connecting to model sever...Traceback (most recent call last):
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6604614550>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.17.0.2', port=56451): Max retries exceeded with url: /server_version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6604614550>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/adversarial_vision_challenge/retry_helper.py", line 21, in retry
    return func(*args, **kwargs)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/adversarial_vision_challenge/client.py", line 98, in _get
    r = self.requests.get(url)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.17.0.2', port=56451): Max retries exceeded with url: /server_version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6604614550>: Failed to establish a new connection: [Errno 111] Connection refused',))
Retrying for the 1. time
 * Serving Flask app "adversarial_vision_challenge.server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 ✓
Server version 1.0.1
Checking model axis and bounds... ✓
Checking return value... ✓
Testing model accuracy on test samples...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:03<00:00, 148.89it/s]
The top-1 performance of your model is 76.4%.

All tests successful, have fun submitting!
```

**Comment by bveliqi** [comment]
Hi @walegahaha,

the test seems to have worked fine, it just took some time for the server to model start, hence the `ConnectionError`s while retrying.

I understand that the logs are very verbose and irritating though - I will try to introduce different log settings for production and local testing each, so you don't have to see those retry mechanism logs until it really finally fails.

**Comment by spMohanty** [comment]
@bveliqi : Yeah those exception messages from the initial retries can be pretty confusing for the participants. Infact they are confusing also when trying to debug the backend. We should try and supress them somehow, only for the initial retries, where we exactly know why they are happenning.

**Comment by walegahaha** [comment]
@bveliqi Thanks. 
another question, using the same command and why sometimes start at step 24/32, 26/32, 31/32 ? For the 24/32 and 26/32, it will re-download them

**Comment by bveliqi** [comment]
@spMohanty will do.

@walegahaha This is how docker / repo2docker an its' cache mechanisms work. Depending on the changes you've made specific layer of the docker image will have to be rebuild or not, hence the different starting points.

**Comment by walegahaha** [comment]
@bveliqi  but I didn't change anything

**Comment by walegahaha** [comment]
@bveliqi 
for example, if I just change a little
fmodel = PyTorchModel(model, bounds=(0,255), num_classes=200)
to
fmodel = PyTorchModel(model, bounds=(0,1), num_classes=200)

it will redownload torch==0.4.0 (484M) and others

**Comment by spMohanty** [comment]
@bveliqi : For local builds we should make a flag available which can simply check if the target image exists, then it skips building it everytime with `crowdai-repo2docker`.
Ofcourse we should put a clear warning that this is dangerous territory, and there are chances your build wont work in the evaluation backend, and you know what you are doing

**Comment by bveliqi** [comment]
@walegahaha @spMohanty I've created #17.
We will look into this the next few days. (Probably not before Monday)

**Comment by bveliqi** [comment]
Done: 2f6af29916ffefe444f20bd1a2a985b2f3198b83
