### ISSUE TITLE
avc-submitt: check if committed changes have been pushed

### ISSUE THREAD

**Issue by bveliqi** [bveliqi/adversarial-vision-challenge#20]
See: https://github.com/bethgelab/adversarial-vision-challenge/blob/master/bin/avc-submit#L23

**Comment by bveliqi** [comment]
Fixed.

**Comment by sun201711** [comment]
I have this problem,can you tell me how to solve this problem?



You have uncommited changes to your repository. Are you sure you want to submit before pushing the latest changes? [y/n]
y
Traceback (most recent call last):
  File "/home/user/shiyu/software/anaconda2/bin/avc-submit", line 76, in <module>
    should_continue = _is_dirty(repo)
  File "/home/user/shiyu/software/anaconda2/bin/avc-submit", line 33, in _is_dirty
    'You have uncommited changes to your repository. Are you sure'
  File "/home/user/shiyu/software/anaconda2/bin/avc-submit", line 18, in _ask_to_continue
    return strtobool(input().lower())
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined

**Comment by bveliqi** [comment]
@sun201711 Which python version are you running this with?

**Comment by sun201711** [comment]
Yeah,I have solved this problem. Thank you!
