### ISSUE TITLE
avc-test-model times out with no error log

### ISSUE THREAD

**Issue by klensink** [bveliqi/adversarial-vision-challenge#31]
I am trying to test a pytorch model, but `avc-test-model` fails with very little information about what may be the cause. 

I think I've narrowed it down to[ this line ](https://github.com/bethgelab/adversarial-vision-challenge/blob/5c61486ae9d096870704800b2685623eff0e5ad6/adversarial_vision_challenge/client.py#L149) where my client asks the model server for it's prediction, but without any more information I cannot figure out what might be going wrong with my model.

I have tested the foolbox model loaded from the same checkpoint locally without any issues, so I am pretty confident the model itself works as intended.

How can I get more accurate logs to figure out where exactly this error is occurring?

Thanks!

Output: 
```
klensink:nips18-avc-model-template$ avc-test-model .
running avc-test-model
running avc-test-setup
Basic setup tests
-----------------
Python version: 3.6
Docker installed & running: ✓
Nvidia-docker installed: ✓
Crowdai_repo2docker installed: ✓
AVC package up-to-date: ✓

Building docker image of submission
-----------------------------------
Submission folder: "."
[Repo2Docker] Looking for repo2docker_config in /home/klensink/GIT/nips18-avc-model-template

FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

# avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Set up locales properly
RUN apt-get update && \
    apt-get install --yes --no-install-recommends locales wget bzip2 && \
    apt-get purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# Use bash as default shell, rather than sh
ENV SHELL /bin/bash

# Set up user
ARG NB_USER
ARG NB_UID
ENV USER ${NB_USER}
ENV HOME /home/${NB_USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER}
WORKDIR ${HOME}

RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
       less \
       npm \
       unzip \
       && apt-get purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8888

# Almost all environment variables
ENV APP_BASE /srv
ENV CONDA_DIR ${APP_BASE}/conda
ENV NB_PYTHON_PREFIX ${CONDA_DIR}
ENV KERNEL_PYTHON_PREFIX ${NB_PYTHON_PREFIX}
# Special case PATH
ENV PATH ${CONDA_DIR}/bin:$HOME/.local/bin:${PATH}
# If scripts required during build are present, copy them

COPY conda/install-miniconda.bash /tmp/install-miniconda.bash

COPY conda/environment.py-3.6.frozen.yml /tmp/environment.yml
RUN bash /tmp/install-miniconda.bash && \
rm /tmp/install-miniconda.bash /tmp/environment.yml



# Copy and chown stuff. This doubles the size of the repo, because
# you can't actually copy as USER, only as root! Thanks, Docker!
USER root
COPY src/ ${HOME}
RUN chown -R ${NB_USER}:${NB_USER} ${HOME}

# Run assemble scripts! These will actually build the specification
# in the repository into the image.
RUN apt-get update && \
apt-get install --yes --no-install-recommends git && \
apt-get purge && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

USER ${NB_USER}
RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"


# Container image Labels!
# Put these at the end, since we don't want to rebuild everything
# when these change! Did I mention I hate Dockerfile cache semantics?


# We always want containers to run as non-root
USER ${NB_USER}

# Make sure that postBuild scripts are marked executable before executing them
# Specify the default command to run
CMD ["jupyter", "notebook", "--ip", "0.0.0.0"]

Using PythonBuildPack builder
Step 1/32 : FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04
 ---> 03608776d6cb
Step 2/32 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 84c241bbd8d1
Step 3/32 : RUN apt-get update &&     apt-get install --yes --no-install-recommends locales wget bzip2 &&     apt-get purge &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> f8c9a017f59d
Step 4/32 : RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
 ---> Using cache
 ---> 56eff1b51e12
Step 5/32 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> 2edf7813bb79
Step 6/32 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 59a22f57b11e
Step 7/32 : ENV LANGUAGE en_US.UTF-8
 ---> Using cache
 ---> aaf8754557a9
Step 8/32 : ENV SHELL /bin/bash
 ---> Using cache
 ---> b3afad930305
Step 9/32 : ARG NB_USER
 ---> Using cache
 ---> 81aff865cb2b
Step 10/32 : ARG NB_UID
 ---> Using cache
 ---> 378dab717bf0
Step 11/32 : ENV USER ${NB_USER}
 ---> Using cache
 ---> fb84c28eb24d
Step 12/32 : ENV HOME /home/${NB_USER}
 ---> Using cache
 ---> 20246a1774fc
Step 13/32 : RUN adduser --disabled-password     --gecos "Default user"     --uid ${NB_UID}     ${NB_USER}
 ---> Using cache
 ---> fdc916f50de3
Step 14/32 : WORKDIR ${HOME}
 ---> Using cache
 ---> 8efb90fa10a8
Step 15/32 : RUN apt-get update &&     apt-get install --yes --no-install-recommends        less        npm        unzip        && apt-get purge &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> f261ad710019
Step 16/32 : EXPOSE 8888
 ---> Using cache
 ---> c9a9d6c9c711
Step 17/32 : ENV APP_BASE /srv
 ---> Using cache
 ---> 5feaf45c045c
Step 18/32 : ENV CONDA_DIR ${APP_BASE}/conda
 ---> Using cache
 ---> c83e9403c0bf
Step 19/32 : ENV NB_PYTHON_PREFIX ${CONDA_DIR}
 ---> Using cache
 ---> c4281f5e321f
Step 20/32 : ENV KERNEL_PYTHON_PREFIX ${NB_PYTHON_PREFIX}
 ---> Using cache
 ---> d228dddc771c
Step 21/32 : ENV PATH ${CONDA_DIR}/bin:$HOME/.local/bin:${PATH}
 ---> Using cache
 ---> 92579265c5e4
Step 22/32 : COPY conda/install-miniconda.bash /tmp/install-miniconda.bash
 ---> Using cache
 ---> 1d298cb4ce7d
Step 23/32 : COPY conda/environment.py-3.6.frozen.yml /tmp/environment.yml
 ---> Using cache
 ---> 6027d2e6d17d
Step 24/32 : RUN bash /tmp/install-miniconda.bash && rm /tmp/install-miniconda.bash /tmp/environment.yml
 ---> Using cache
 ---> 7e540595b42f
Step 25/32 : USER root
 ---> Using cache
 ---> 135b85bbaa21
Step 26/32 : COPY src/ ${HOME}
 ---> 6e2c002167d5
Step 27/32 : RUN chown -R ${NB_USER}:${NB_USER} ${HOME}
 ---> Running in 3879fe8f378e
Removing intermediate container 3879fe8f378e
 ---> c05675d52bae
Step 28/32 : RUN apt-get update && apt-get install --yes --no-install-recommends git && apt-get purge && apt-get clean && rm -rf /var/lib/apt/lists/*
 ---> Running in 51606a6fb155
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Ign:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Ign:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
Get:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release [564 B]
Get:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release [564 B]
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg [801 B]
Get:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release.gpg [801 B]
Get:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages [136 kB]
Get:10 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Packages [25.2 kB]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [85.7 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:14 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [676 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9,802 kB]
Get:16 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.7 kB]
Get:17 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [458 kB]
Get:18 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3,746 B]
Get:19 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1,558 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:21 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9,827 kB]
Get:22 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:23 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [273 kB]
Get:24 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1,060 kB]
Get:25 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.1 kB]
Get:26 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [870 kB]
Get:27 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [18.8 kB]
Get:28 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [7,321 B]
Get:29 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [8,086 B]
Fetched 25.6 MB in 9s (2,568 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  git-man liberror-perl libgdbm3 libperl5.22 perl perl-modules-5.22
Suggested packages:
  gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-el git-email
  git-gui gitk gitweb git-arch git-cvs git-mediawiki git-svn perl-doc
  libterm-readline-gnu-perl | libterm-readline-perl-perl make
Recommended packages:
  patch rsync ssh-client netbase rename
The following NEW packages will be installed:
  git git-man liberror-perl libgdbm3 libperl5.22 perl perl-modules-5.22
0 upgraded, 7 newly installed, 0 to remove and 15 not upgraded.
Need to get 10.2 MB of archives.
After this operation, 64.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libgdbm3 amd64 1.8.3-13.1 [16.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 perl-modules-5.22 all 5.22.1-9ubuntu0.5 [2,645 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libperl5.22 amd64 5.22.1-9ubuntu0.5 [3,396 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 perl amd64 5.22.1-9ubuntu0.5 [238 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial/main amd64 liberror-perl all 0.17-1.2 [19.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 git-man all 1:2.7.4-0ubuntu1.4 [736 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 git amd64 1:2.7.4-0ubuntu1.4 [3,158 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 10.2 MB in 4s (2,175 kB/s)
Selecting previously unselected package libgdbm3:amd64.
(Reading database ... 11969 files and directories currently installed.)
Preparing to unpack .../libgdbm3_1.8.3-13.1_amd64.deb ...
Unpacking libgdbm3:amd64 (1.8.3-13.1) ...
Selecting previously unselected package perl-modules-5.22.
Preparing to unpack .../perl-modules-5.22_5.22.1-9ubuntu0.5_all.deb ...
Unpacking perl-modules-5.22 (5.22.1-9ubuntu0.5) ...
Selecting previously unselected package libperl5.22:amd64.
Preparing to unpack .../libperl5.22_5.22.1-9ubuntu0.5_amd64.deb ...
Unpacking libperl5.22:amd64 (5.22.1-9ubuntu0.5) ...
Selecting previously unselected package perl.
Preparing to unpack .../perl_5.22.1-9ubuntu0.5_amd64.deb ...
Unpacking perl (5.22.1-9ubuntu0.5) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../liberror-perl_0.17-1.2_all.deb ...
Unpacking liberror-perl (0.17-1.2) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a2.7.4-0ubuntu1.4_all.deb ...
Unpacking git-man (1:2.7.4-0ubuntu1.4) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.7.4-0ubuntu1.4_amd64.deb ...
Unpacking git (1:2.7.4-0ubuntu1.4) ...
Setting up libgdbm3:amd64 (1.8.3-13.1) ...
Setting up perl-modules-5.22 (5.22.1-9ubuntu0.5) ...
Setting up libperl5.22:amd64 (5.22.1-9ubuntu0.5) ...
Setting up perl (5.22.1-9ubuntu0.5) ...
update-alternatives: using /usr/bin/prename to provide /usr/bin/rename (rename) in auto mode
Setting up liberror-perl (0.17-1.2) ...
Setting up git-man (1:2.7.4-0ubuntu1.4) ...
Setting up git (1:2.7.4-0ubuntu1.4) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
Removing intermediate container 51606a6fb155
 ---> 79e4af3f74d6
Step 29/32 : USER ${NB_USER}
 ---> Running in f6df045b44c3
Removing intermediate container f6df045b44c3
 ---> 71502434f7d1
Step 30/32 : RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"
 ---> Running in 7b4a2bdcd82d
Collecting git+https://github.com/bethgelab/adversarial-vision-challenge (from -r requirements.txt (line 4))
  Cloning https://github.com/bethgelab/adversarial-vision-challenge to /tmp/pip-2mpj0lfa-build
Collecting foolbox==1.3.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/be/55/602e75a37e17c0878201e014369c63651f87b0015168efa2efed533b053a/foolbox-1.3.1.tar.gz (226kB)
Collecting torch==0.4.1 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/49/0e/e382bcf1a6ae8225f50b99cc26effa2d4cc6d66975ccf3fa9590efcbedce/torch-0.4.1-cp36-cp36m-manylinux1_x86_64.whl (519.5MB)
Collecting torchvision==0.2.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/ca/0d/f00b2885711e08bd71242ebe7b96561e6f6d01fdb4b9dcf4d37e2e13c5e1/torchvision-0.2.1-py2.py3-none-any.whl (54kB)
Collecting bson (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/7b/f7/d69945b0cc699977fb60421b24875a6519503ce9d2b8b59859993544be8d/bson-0.5.6.tar.gz
Collecting flask (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl (91kB)
Collecting numpy (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/88/29/f4c845648ed23264e986cdc5fbab5f8eace1be5e62144ef69ccc7189461d/numpy-1.15.0-cp36-cp36m-manylinux1_x86_64.whl (13.9MB)
Collecting pillow (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/d1/24/f53ff6b61b3d728b90934bddb4f03f8ab584a7f49299bf3bde56e2952612/Pillow-5.2.0-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)
Requirement already satisfied: requests in /srv/conda/lib/python3.6/site-packages (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Requirement already satisfied: setuptools in /srv/conda/lib/python3.6/site-packages (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Collecting pyyaml (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
Collecting crowdai_api (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/f1/7f/6e99959bd9f99437ea1604e21128a54598bd46c738178347b4ad4381a166/crowdai_api-0.1.14.tar.gz
Collecting GitPython (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/fe/e5/fafe827507644c32d6dc553a1c435cdf882e0c28918a5bab29f7fbebfb70/GitPython-2.1.11-py2.py3-none-any.whl (448kB)
Collecting packaging (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/ad/c2/b500ea05d5f9f361a562f089fc91f77ed3b4783e13a08a3daf82069b1224/packaging-17.1-py2.py3-none-any.whl
Collecting future (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
Collecting tqdm (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/7d/e6/19dfaff08fcbee7f3453e5b537e65a8364f1945f921a36d08be1e2ff3475/tqdm-4.24.0-py2.py3-none-any.whl (43kB)
Collecting crowdai-repo2docker (from adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/98/c8/2a2e30ac420d3c8f35007297bf8bccf0d803b8cc7f5fde329f2f5e8bfeb4/crowdai_repo2docker-0.5.0-py2.py3-none-any.whl (60kB)
Collecting scipy (from foolbox==1.3.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a8/0b/f163da98d3a01b3e0ef1cab8dd2123c34aee2bafbb1c5bffa354cc8a1730/scipy-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (31.2MB)
Requirement already satisfied: six in /srv/conda/lib/python3.6/site-packages (from torchvision==0.2.1->-r requirements.txt (line 3))
Requirement already satisfied: python-dateutil>=2.4.0 in /srv/conda/lib/python3.6/site-packages (from bson->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Requirement already satisfied: Jinja2>=2.10 in /srv/conda/lib/python3.6/site-packages (from flask->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Collecting click>=5.1 (from flask->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
Collecting Werkzeug>=0.14 (from flask->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
Collecting itsdangerous>=0.24 (from flask->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz (46kB)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /srv/conda/lib/python3.6/site-packages (from requests->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Requirement already satisfied: idna<2.7,>=2.5 in /srv/conda/lib/python3.6/site-packages (from requests->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /srv/conda/lib/python3.6/site-packages (from requests->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Requirement already satisfied: certifi>=2017.4.17 in /srv/conda/lib/python3.6/site-packages (from requests->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Collecting python-gitlab>=1.3.0 (from crowdai_api->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/d6/29/56dcfa743d4fcb29af9258a83b644a81decdf82fdeaf76d6c9f3a2085a77/python-gitlab-1.5.1.tar.gz (107kB)
Collecting redis (from crowdai_api->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/3b/f6/7a76333cf0b9251ecf49efff635015171843d9b977e4ffcf59f9c4428052/redis-2.10.6-py2.py3-none-any.whl (64kB)
Collecting gitdb2>=2.0.0 (from GitPython->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/a9/fb/d3afc4e2a8d506a07af19f125f7a473ae1b56f942ed2ba80776eb8ae23b1/gitdb2-2.0.4-py2.py3-none-any.whl (62kB)
Collecting pyparsing>=2.0.2 (from packaging->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
Collecting ruamel.yaml>=0.15 (from crowdai-repo2docker->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/4b/bc/c7a08688723a6327f000645babe33e92bbcd983effaa297180f3850d76bd/ruamel.yaml-0.15.47-cp36-cp36m-manylinux1_x86_64.whl (637kB)
Collecting escapism (from crowdai-repo2docker->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/d2/28/0f93611a7b8f50a5d22a576af9fe06af32abe5e2c47f09f64e39f8ea6dc3/escapism-1.0.0-py2.py3-none-any.whl
Collecting python-json-logger (from crowdai-repo2docker->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/3a/ed/2ba5a2dfce45fa67e0588dd6457b59ffdef7f1fdcd2c1152e085e3c9a726/python_json_logger-0.1.9-py2.py3-none-any.whl
Collecting docker (from crowdai-repo2docker->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/a5/64/8c0a5d22e70257e6b7ef7f14b577f99f0b9b1560c604f87856d0db80d151/docker-3.4.1-py2.py3-none-any.whl (124kB)
Requirement already satisfied: traitlets in /srv/conda/lib/python3.6/site-packages (from crowdai-repo2docker->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Requirement already satisfied: MarkupSafe>=0.23 in /srv/conda/lib/python3.6/site-packages (from Jinja2>=2.10->flask->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->GitPython->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/0f/14/e3112808b727f72df9531fc2f00b84d4966e66001748b6883a21c767e902/smmap2-2.0.4-py2.py3-none-any.whl
Collecting docker-pycreds>=0.3.0 (from docker->crowdai-repo2docker->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/ea/bf/7e70aeebc40407fbdb96fa9f79fc8e4722ea889a99378303e3bcc73f4ab5/docker_pycreds-0.3.0-py2.py3-none-any.whl
Collecting websocket-client>=0.32.0 (from docker->crowdai-repo2docker->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/8a/a1/72ef9aa26cfe1a75cee09fc1957e4723add9de098c15719416a1ee89386b/websocket_client-0.48.0-py2.py3-none-any.whl (198kB)
Requirement already satisfied: decorator in /srv/conda/lib/python3.6/site-packages (from traitlets->crowdai-repo2docker->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Requirement already satisfied: ipython-genutils in /srv/conda/lib/python3.6/site-packages (from traitlets->crowdai-repo2docker->adversarial-vision-challenge==1.0.3->-r requirements.txt (line 4))
Installing collected packages: numpy, scipy, foolbox, torch, pillow, torchvision, bson, click, Werkzeug, itsdangerous, flask, pyyaml, python-gitlab, redis, crowdai-api, smmap2, gitdb2, GitPython, pyparsing, packaging, future, tqdm, ruamel.yaml, escapism, python-json-logger, docker-pycreds, websocket-client, docker, crowdai-repo2docker, adversarial-vision-challenge
  Running setup.py install for foolbox: started
    Running setup.py install for foolbox: finished with status 'done'
  Running setup.py install for bson: started
    Running setup.py install for bson: finished with status 'done'
  Running setup.py install for itsdangerous: started
    Running setup.py install for itsdangerous: finished with status 'done'
  Running setup.py install for pyyaml: started
    Running setup.py install for pyyaml: finished with status 'done'
  Running setup.py install for python-gitlab: started
    Running setup.py install for python-gitlab: finished with status 'done'
  Running setup.py install for crowdai-api: started
    Running setup.py install for crowdai-api: finished with status 'done'
  Running setup.py install for future: started
    Running setup.py install for future: finished with status 'done'
  Running setup.py install for adversarial-vision-challenge: started
    Running setup.py install for adversarial-vision-challenge: finished with status 'done'
Successfully installed GitPython-2.1.11 Werkzeug-0.14.1 adversarial-vision-challenge-1.0.3 bson-0.5.6 click-6.7 crowdai-api-0.1.14 crowdai-repo2docker-0.5.0 docker-3.4.1 docker-pycreds-0.3.0 escapism-1.0.0 flask-1.0.2 foolbox-1.3.1 future-0.16.0 gitdb2-2.0.4 itsdangerous-0.24 numpy-1.15.0 packaging-17.1 pillow-5.2.0 pyparsing-2.2.0 python-gitlab-1.5.1 python-json-logger-0.1.9 pyyaml-3.13 redis-2.10.6 ruamel.yaml-0.15.47 scipy-1.1.0 smmap2-2.0.4 torch-0.4.1 torchvision-0.2.1 tqdm-4.24.0 websocket-client-0.48.0
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 7b4a2bdcd82d
 ---> f0b4e1fed1e3
Step 31/32 : USER ${NB_USER}
 ---> Running in ea8c85056d33
Removing intermediate container ea8c85056d33
 ---> b567e7203d6e
Step 32/32 : CMD ["jupyter", "notebook", "--ip", "0.0.0.0"]
 ---> Running in d7e0f254e3c0
Removing intermediate container d7e0f254e3c0
 ---> 62631cff0cf9
{"aux": {"ID": "sha256:62631cff0cf9922c45b037f8091e7c97a010d5c686aba6d4e37eb70a934b1492"}}Successfully built 62631cff0cf9
Successfully tagged avc/model_submission:latest
Building image from cache (if exists)... ✓
avc_test_model_submission
Removing existing submission container... ✓
Starting container on port 33426 using the command 
 
 NV_GPU=0 nvidia-docker run --expose=33426 -d -p 33426:33426 -v /home/klensink/GIT/nips18-avc-model-template:/prd -e GPU=0 -e MODEL_PORT=33426 --name=avc_test_model_submission avc/model_submission bash /prd/run.sh
fc5bb5971a955fcf62a21cbf41eb0ab59ddeebc3615baf23424496e47d914f4f
Received IP of server:  172.17.0.2
Wating for model server to start...
Retrying for the 1. time
CREATING FMODEL
Retrying for the 2. time
CREATING MODEL SERVER
 * Serving Flask app "adversarial_vision_challenge.server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Connecting to model sever... ✓
Server version 1.0.3
Checking model axis and bounds... ✓
Retrying for the 1. time
Retrying for the 2. time
Retrying for the 3. time
Retried request for 3 times. Giving up.
Checking return value...Traceback (most recent call last):
  File "/home/klensink/anaconda3/bin/avc-test-model", line 172, in <module>
    no_build=args.no_build, gpu=args.gpu)
  File "/home/klensink/anaconda3/bin/avc-test-model", line 130, in test_model
    assert isinstance(model(image), int), \
  File "/home/klensink/anaconda3/lib/python3.6/site-packages/adversarial_vision_challenge/client.py", line 144, in __call__
    return self.predict(image)
  File "/home/klensink/anaconda3/lib/python3.6/site-packages/adversarial_vision_challenge/client.py", line 149, in predict
    result = self._post('/predict', data)
  File "/home/klensink/anaconda3/lib/python3.6/site-packages/adversarial_vision_challenge/retry_helper.py", line 26, in retry
    "Failed already {0} times. No further retrying.".format(retries))
adversarial_vision_challenge.retry_helper.RetriesExceededError: Failed already 3 times. No further retrying.
```

**Comment by klensink** [comment]
If it helps, I am making the model like so: https://gitlab.crowdai.org/XtractAI/nips18-avc-model-template

**Comment by bveliqi** [comment]
@klensink: Can you please run `docker logs avc_test_model_submission` after this happens and post the logs here.
It looks like the docker-container running the model server crashes after it has initially started successfully. The logs might tell why this is happening...

**Comment by klensink** [comment]
@bveliqi Thank you for the help, I was able to use these logs to find out that my pre-processing was not behaving as expected.
