### ISSUE TITLE
ZeroDivisionError in avc-test-attack

### ISSUE THREAD

**Issue by csy530216** [bveliqi/adversarial-vision-challenge#32]
When I ran `avc-test-untargeted-attack .` under saltnpepper_untargeted_attack_baseline, the following error message showed:
> ...
Starting to test attack against mock model and test samples...
If you would like to test with less or more samples, append e.g --samples 50 to your avc-test-XXX command.
  0%|                                                                                                          | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/shuyu/anaconda3/bin/avc-test-attack", line 350, in <module>
    gpu=args.gpu, mode=args.mode, samples=args.samples)
  File "/home/shuyu/anaconda3/bin/avc-test-attack", line 257, in test_attack
    elif (time.time() - start_time - 50) / float(len(result_files)) > 20:
ZeroDivisionError: float division by zero

The relevant code in avc-test-attack:
```python
with tqdm(total=len(test_samples)) as pbar:
    while True:
        time.sleep(1)
        result_files = os.listdir('avc_results/')
        num_results = len(result_files)
        # print('{} result files written after {} seconds.'.format(
        #     len(result_files), int(time.time() - start_time)))

        # update progress bar
        if pbar.n < num_results:
            pbar.update(num_results - pbar.n)

        # check that results are written within time limit
        if num_results == 0 and time.time() - start_time > 50:
            raise RuntimeError('Results file not written with time limit'
                                ' (50 seconds)- something went wrong!')
        elif (time.time() - start_time - 50) / float(len(result_files)) > 20:
            raise RuntimeError('Your attack is too slow'
                                ' (> 20 seconds / sample)!')

        # end condition
        if num_results == len(test_samples):
            break

        containers = str(subprocess.check_output('docker ps', shell=True))
        if 'avc_test_attack' not in containers:
            print("""Your container stopped running before all images
            were processed. This either means that the attack was not
            able to produce adversarials for all samples or that the
            attack stopped because of runtime errors.""")
            break
```
I think that the code intends to check the results once every second, but when time.time() - start_time <= 50 and before the attack creates one adversarial image, `num_results == 0 and time.time() - start_time > 50` is false but `len(result_files)`==0, so the ZeroDivisionError happens. After deleting
```python
        elif (time.time() - start_time - 50) / float(len(result_files)) > 20:
            raise RuntimeError('Your attack is too slow'
                                ' (> 20 seconds / sample)!')
```
the tests ran successfully.

**Comment by csy530216** [comment]
Maybe the code should be modified as follows:
```python
if num_results == 0 and time.time() - start_time > 50:
	raise RuntimeError('Results file not written with time limit'
					   ' (50 seconds)- something went wrong!')
elif num_results != 0 and (time.time() - start_time) / float(num_results) > 20:
	raise RuntimeError('Your attack is too slow'
					   ' (> 20 seconds / sample)!')
```
or like what the script `avc-test-model-against-attack` does:
```python
if num_results == 0 and time.time() - start_time > 19:
    raise RuntimeError('Results file not written with time limit'
                        ' (20 seconds)- something went wrong!')
elif time.time() - start_time > 21 and \
        (time.time() - start_time) / float(len(result_files)) > 10:
    raise RuntimeError('Your attack is too slow'
                        ' (> 10 seconds / sample)!')
```

**Comment by jonasrauber** [comment]
yes, you are right; we will fix this! thanks for reporting it!
