### ISSUE TITLE
avc-test-model . does not work for offical resnet18_model_baseline

### ISSUE THREAD

**Issue by ZiangYan** [bveliqi/adversarial-vision-challenge#33]
Hi, 

I'm trying to start with the offical resnet18 model from [https://gitlab.crowdai.org/adversarial-vision-challenge/resnet18_model_baseline](https://gitlab.crowdai.org/adversarial-vision-challenge/resnet18_model_baseline)

I fork this repo to my own gitlab, and submit it with 
```
avc-submit .
```
everything seems fine, and I can view my score in the leaderboard.

The problem is I can not test it in local. After running
```
avc-test-model .
```
the final error log is 
```
 NV_GPU=0 nvidia-docker run --expose=39108 -d -p 39108:39108 -v /xxx/resnet18_model_baseline:/prd -e GPU=0 -e MODEL_PORT=39108 --name=avc_test_model_submission avc/model_submission bash /prd/run.sh
61ea0ee1d2f9c2fa92362cd6924723ac69950bdd8ba4657f8582f64ec82d0916
Received IP of server:  172.17.0.2
Wating for model server to start...
 * Serving Flask app "adversarial_vision_challenge.server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Retrying for the 1. time
Retrying for the 2. time
Retrying for the 3. time
Retried request for 3 times. Giving up.
Connecting to model sever...Traceback (most recent call last):
  File "/usr/local/bin/avc-test-model", line 177, in <module>
    no_build=args.no_build, gpu=args.gpu)
  File "/usr/local/bin/avc-test-model", line 116, in test_model
    _wait_for_server_start(model)
  File "/usr/local/lib/python3.5/dist-packages/adversarial_vision_challenge/utils.py", line 79, in _wait_for_server_start
    version = model.server_version()
  File "/usr/local/lib/python3.5/dist-packages/adversarial_vision_challenge/client.py", line 141, in server_version
    return self._get('/server_version')
  File "/usr/local/lib/python3.5/dist-packages/adversarial_vision_challenge/retry_helper.py", line 24, in retry
    CrowdAiNotifier.retries_exceeded()
  File "/usr/local/lib/python3.5/dist-packages/adversarial_vision_challenge/notifier.py", line 62, in retries_exceeded
    "type": AttackNotifications.TYPE
  File "/usr/local/lib/python3.5/dist-packages/adversarial_vision_challenge/notifier.py", line 31, in _send_notification
    crowdai_events.register_event(event_type, message, payload, blocking)
TypeError: register_event() takes from 2 to 4 positional arguments but 5 were given
```

It seems that I need to start the "model_server" somehow. But currently I can not find anything useful after google.

**Comment by jonasrauber** [comment]
can you report the docker logs of the model container?

**Comment by jonasrauber** [comment]
closed because no activity

**Comment by yxchng** [comment]
@jonasrauber How to get the logs you want? I am also facing the same problem.

**Comment by yxchng** [comment]
@jonasrauber The following is probably the log you want:

```
Starting model server...
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/yxchng/.torch/models/resnet18-5c106cde.pth
100%|██████████| 46827520/46827520 [00:04<00:00, 11673196.75it/s]
client <-> server interaction verifier id: 4a98f55c-bc10-11e8-83c5-0242ac110003
Client <-> Server interaction monitor started...
client <-> server interaction verifier id: 4a99075e-bc10-11e8-83c5-0242ac110003
starting server on port 44189
 * Serving Flask app "adversarial_vision_challenge.server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
/srv/conda/lib/python3.6/site-packages/foolbox/models/pytorch.py:63: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  images = Variable(images, volatile=True)
Exception on /predict [POST]
Traceback (most recent call last):
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/conda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 109, in predict
    prediction = _predict(request)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 214, in wrapper
    result = function(**args)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 80, in _predict
    prediction = model.predictions(image)
  File "/srv/conda/lib/python3.6/site-packages/foolbox/models/base.py", line 122, in predictions
    return np.squeeze(self.batch_predictions(image[np.newaxis]), axis=0)
  File "/srv/conda/lib/python3.6/site-packages/foolbox/models/pytorch.py", line 64, in batch_predictions
    predictions = self._model(images)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/torchvision/models/resnet.py", line 149, in forward
    x = self.avgpool(x)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 547, in forward
    self.padding, self.ceil_mode, self.count_include_pad)
RuntimeError: Given input size: (512x2x2). Calculated output size: (512x-4x-4). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:63
Exception on /predict [POST]
Traceback (most recent call last):
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/conda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 109, in predict
    prediction = _predict(request)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 214, in wrapper
    result = function(**args)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 80, in _predict
    prediction = model.predictions(image)
  File "/srv/conda/lib/python3.6/site-packages/foolbox/models/base.py", line 122, in predictions
    return np.squeeze(self.batch_predictions(image[np.newaxis]), axis=0)
  File "/srv/conda/lib/python3.6/site-packages/foolbox/models/pytorch.py", line 64, in batch_predictions
    predictions = self._model(images)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/torchvision/models/resnet.py", line 149, in forward
    x = self.avgpool(x)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 547, in forward
    self.padding, self.ceil_mode, self.count_include_pad)
RuntimeError: Given input size: (512x2x2). Calculated output size: (512x-4x-4). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:63
Exception on /predict [POST]
Traceback (most recent call last):
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/conda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 109, in predict
    prediction = _predict(request)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 214, in wrapper
    result = function(**args)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 80, in _predict
    prediction = model.predictions(image)
  File "/srv/conda/lib/python3.6/site-packages/foolbox/models/base.py", line 122, in predictions
    return np.squeeze(self.batch_predictions(image[np.newaxis]), axis=0)
  File "/srv/conda/lib/python3.6/site-packages/foolbox/models/pytorch.py", line 64, in batch_predictions
    predictions = self._model(images)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/torchvision/models/resnet.py", line 149, in forward
    x = self.avgpool(x)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 547, in forward
    self.padding, self.ceil_mode, self.count_include_pad)
RuntimeError: Given input size: (512x2x2). Calculated output size: (512x-4x-4). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:63
Exception on /predict [POST]
Traceback (most recent call last):
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/conda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/conda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 109, in predict
    prediction = _predict(request)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 214, in wrapper
    result = function(**args)
  File "/srv/conda/lib/python3.6/site-packages/adversarial_vision_challenge/server.py", line 80, in _predict
    prediction = model.predictions(image)
  File "/srv/conda/lib/python3.6/site-packages/foolbox/models/base.py", line 122, in predictions
    return np.squeeze(self.batch_predictions(image[np.newaxis]), axis=0)
  File "/srv/conda/lib/python3.6/site-packages/foolbox/models/pytorch.py", line 64, in batch_predictions
    predictions = self._model(images)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/torchvision/models/resnet.py", line 149, in forward
    x = self.avgpool(x)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 547, in forward
    self.padding, self.ceil_mode, self.count_include_pad)
RuntimeError: Given input size: (512x2x2). Calculated output size: (512x-4x-4). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:63
```

I am very puzzled by it. Is it saying the input size is 2x2? Isn't the input size 64x64?

**Comment by bveliqi** [comment]
Hi @yxchng, could you please open a new issue in future, instead commenting an already closed one opened by someone else?

Would you please give me the link to the repository you're trying to submit? I assume this is not the unmodified ResNet18 baseline model as stated by the initial issue opener?
